### ISSUE TITLE
error message while ./configure

### ISSUE THREAD

**Issue by benpptung** [infusion/PHP-Facedetect#2]
Hi..today, I'm trying to compile this great extension, but got the following error message

checking /usr/local/include/opencv/cv.h usability... no
checking /usr/local/include/opencv/cv.h presence... no
checking for /usr/local/include/opencv/cv.h... no
configure: error: 'opencv/cv.h' header not found

I've installed opencv 2.3.1 on my FreeBSD 8.2 box by using FreeBSD port tree, while checking /usr/local/include/opencv/cv.h, the header is exist there. I have no idea what's wrong, do you have any advice? 

thank you / Ben

**Comment by SAPessi** [comment]
I've had a couple of problems installing on MacOS. First, configure complained that it couldn't find opencv/cv.h and then that the wrong version of OpenCV:
configure: error: wrong OpenCV version or OpenCV not found

If you look at the configure.log you find that the root cause of the issue is that cv.h is trying to include opencv2/core/core_c.h and cannot find it.

The issue in my case was because CFLAGS and LDFLAGS were not set. I compiled OpenCV manually on my mac and installed it under /usr/local. Simply exporting the correct paths for autoconf fixed the configuration issue for me:

```
export CFLAGS="$CFLAGS -I/usr/local/include"
export LDFLAGS="$LDFLAGS -L/usr/local/lib"
```

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
