### ISSUE TITLE
./configure failed

### ISSUE THREAD

**Issue by thibaultmeyer** [infusion/PHP-Facedetect#6]
hi,

i have install the latest version of OpenCV but i cant complete ./configure ...

checking /usr/include/opencv/cv.h usability... yes
checking /usr/include/opencv/cv.h presence... yes
checking for /usr/include/opencv/cv.h... yes
checking /usr/include/opencv/highgui.h usability... yes
checking /usr/include/opencv/highgui.h presence... yes
checking for /usr/include/opencv/highgui.h... yes
checking for cvLoad in -lopencv_objdetect... no
configure: error: wrong OpenCV version or OpenCV not found
# 

root@severnaya> ls -l /usr/lib | grep opencv_objdetect                                2
lrwxrwxrwx  1 root root    26 Dec 20 20:14 libopencv_objdetect.so -> libopencv_objdetect.so.2.3
lrwxrwxrwx  1 root root    28 Dec 20 20:14 libopencv_objdetect.so.2.3 -> libopencv_objdetect.so.2.3.1
-rwxr-xr-x  1 root root  366K Dec 20 20:14 libopencv_objdetect.so.2.3.1

**Comment by SAPessi** [comment]
I've had a couple of problems installing on MacOS. First, configure complained that it couldn't find opencv/cv.h and then that the wrong version of OpenCV:
configure: error: wrong OpenCV version or OpenCV not found

If you look at the configure.log you find that the root cause of the issue is that cv.h is trying to include opencv2/core/core_c.h and cannot find it.

The issue in my case was because CFLAGS and LDFLAGS were not set. I compiled OpenCV manually on my mac and installed it under /usr/local. Simply exporting the correct paths for autoconf fixed the configuration issue for me:

```
export CFLAGS="$CFLAGS -I/usr/local/include"
export LDFLAGS="$LDFLAGS -L/usr/local/lib"
```

**Comment by infusion** [comment]
Could you guys please test the current master branch? I rewrote the code almost completely for PHP7 and to come by the old OpenCV C-interface.
